#Numpy- Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operation


In [46]:
import numpy as np

List v/s Numpy -> Time Taken

In [47]:
from time import process_time

In [48]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)


0.0006256879999995135


In [49]:
num_array = np.array([i for i in range(10000)])
start_time = process_time()
num_array += 5
end_time = process_time()
print(end_time - start_time)

0.0001476039999985801


Numpy Array

In [50]:
#creating 1D array
np_array = np.array([1,2,3,4,5])
print(np_array)
print(np_array.shape)
type(np_array)


[1 2 3 4 5]
(5,)


numpy.ndarray

In [51]:
#creating multidimensional array
b = np.array([(1,2,3),(5,6,7)])
print(b)
print(b.shape)


[[1 2 3]
 [5 6 7]]
(2, 3)


In [52]:
c = np.array([1,2,4,5,6,7,3],dtype = float)
c

array([1., 2., 4., 5., 6., 7., 3.])

Initial Placeholders in numpy array

In [53]:
#create a numpy array of zeros
x =np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [54]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [55]:
#array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [56]:
#create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [57]:
#create a numpy array with random values --->by default it gives the value between zero and one
b = np.random.random((3,4))
print(b)

[[0.31826741 0.0505684  0.18154194 0.46585209]
 [0.22721649 0.25305273 0.67247928 0.72414253]
 [0.6652214  0.40747787 0.5689168  0.54937203]]


In [58]:
#random integer values array in a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[56 89 61 66 46]
 [77 94 69 31 74]
 [50 53 44 31 76]]


In [59]:
#create an array of evenly spaced values -->specifying the number of values requires
d= np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [60]:
#create an array of evenly spaced values -->specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [61]:
#convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a Numpy array

In [62]:
c=np.random.randint(10,90,(5,5))
print(c)

[[71 20 73 77 13]
 [20 24 37 36 14]
 [30 78 64 84 61]
 [66 32 65 64 32]
 [14 75 11 24 34]]


In [63]:
#array dimension -> gives the number of rows and cols
print(c.shape)

(5, 5)


In [64]:
#number of dimension
print(c.ndim)

2


In [65]:
#number of elements in the array
print(c.size)

25


In [66]:
#checking the data type of the values in the array
print(c.dtype)

int64


Mathematical Operation on Numpy Array

In [67]:
list1 = [1,2,3,4,5]
list2 = [5,6,7,8,9]
print(list1 + list2) #concatenate or joins two list

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]


In [68]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[4 6 8]
 [0 7 6]
 [8 1 0]]
[[17 18 16]
 [16 14 15]
 [19 16 19]]


In [69]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[21 24 24]
 [16 21 21]
 [27 17 19]]
[[-13 -12  -8]
 [-16  -7  -9]
 [-11 -15 -19]]
[[ 68 108 128]
 [  0  98  90]
 [152  16   0]]
[[0.23529412 0.33333333 0.5       ]
 [0.         0.5        0.4       ]
 [0.42105263 0.0625     0.        ]]


In [70]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[21 24 24]
 [16 21 21]
 [27 17 19]]
[[-13 -12  -8]
 [-16  -7  -9]
 [-11 -15 -19]]
[[ 68 108 128]
 [  0  98  90]
 [152  16   0]]
[[0.23529412 0.33333333 0.5       ]
 [0.         0.5        0.4       ]
 [0.42105263 0.0625     0.        ]]


Array Manipulation

In [71]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 5 9]
 [4 4 9]]
(2, 3)


In [72]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 4]
 [5 4]
 [9 9]]
(3, 2)


In [73]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 4]
 [5 4]
 [9 9]]
(3, 2)


In [74]:
#reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

b= a.reshape(3,2)
print(b)
print(b.shape)

[[2 1 7]
 [3 5 2]]
(2, 3)
[[2 1]
 [7 3]
 [5 2]]
(3, 2)
